### ISSUE TITLE
Inconsistent result between get_all and get

### ISSUE THREAD

**Issue by lanzer** [darkrishabh/react-native-db-models#11]
When using get_all, the result set looks like:
{autoinc:12,
rows:{_id:queried_data ...},
totalrows:3}

But when I used get, the result set looks like:
[queried_data ...]

It'd be good to have consistency in results, and have query results always under result.rows, or none at all.  Including metadata like result.totalrows is helpful and more consistent with other DBA out there.

Another nice to have is to include output format for each command in the README.

Keep up the great work!

**Comment by darkrishabh** [comment]
Thank @lanzer I will surely take a look, and if you can create a PR for this, it will be more than just helpful.
