### ISSUE TITLE
multiple inserts doesn't work

### ISSUE THREAD

**Issue by anchetaWern** [darkrishabh/react-native-db-models#14]
I'm trying to do the following:

```
DB.news.add({'title': 'abc', 'url': 'def'});
DB.news.add({'title': 'ghi', 'url': 'jkl'});
DB.news.add({'title': 'mno', 'url': 'pqr'});
DB.news.add({'title': 'stu', 'url': 'vwx'});
```

But only the last row gets inserted. I tested it by tapping on reload js on the app then waited for a few seconds. And then I replaced the code above with the following and tap on reload js again to reflect the changes:

```
DB.news.get_all(function(data){
    alert(data.totalrows);
});
```

It's only returning 1 instead of the expected output which is 4.

Any ideas?

**Comment by darkrishabh** [comment]
Hi @anchetaWern 

Did you try add_all method.

It's not in the docs, but it was made for this purpose.

DB.news.add_all([
{'title': 'abc', 'url': 'def'},
{'title': 'ghi', 'url': 'jkl'},
{'title': 'mno', 'url': 'pqr'},
{'title': 'stu', 'url': 'vwx'}
])

**Comment by darkrishabh** [comment]
I am closing this issue, as the add_all will do the work.
