### ISSUE TITLE
erase_db() not erasing all data.

### ISSUE THREAD

**Issue by ys27** [darkrishabh/react-native-db-models#20]
Hi, I am having an issue where using erase_db with more than 15 items doesn't erase all values. Specifically, these are of index 12 and 13, if they are of use. Thank you.

**Comment by ys27** [comment]
remove also doesnt seem to be working.

**Comment by waleedarshad-vf** [comment]
I am facing same issue. is it really an issue or the way we are dealing is wrong ? @ys27 @por @darkrishabh @mcnamee ?

**Comment by greyvugrin** [comment]
@ys27 @waleedarshad-vf I had luck when I removed a `.get` call that was right after the remove. Seems to be something to do with timing there. See #26
