### ISSUE TITLE
Getting an object

### ISSUE THREAD

**Issue by FSpierckel** [darkrishabh/react-native-db-models#8]
Hello,

I'm adding an object into the db, this object is : 

```
var barcode = {
 value: barcodeValue,
 format: barcodeFormat
}
```

I add this barcode with the method : 

```
class BarcodeDAO {
 add_new_barcode(barcode,success) {
    DB.barcodes.add({barcode},success)
  }

  get_all_barcodes(success) {
    DB.barcodes.get_all(success);
  }

  remove_barcode(barcode,success) {
    DB.barcodes.remove(
     {barcode}, function(removed_data){
      console.log(removed_data);
  });
  }
 }
```

The problem is that the remove or get function doesn't work when I pass an object. My values are correct (I checked them with the debugger).

Is there a way to do that or I have to add my data like data : {value: barcodeValue, format: barcodeFormat} (this solution is working)?

**Comment by waleedarshad-vf** [comment]
Same problem. what did you use?

**Comment by waleedarshad-vf** [comment]
@Spierki

**Comment by FSpierckel** [comment]
@waleedarshad-vf I used the solution at the end of my post
